[flake8]
max-line-length = 120
ignore=
  E111, # Indentation is not a multiple of four
  E114, # Indentation is not a multiple of four (comment)
  E121, # continuation line under-indented for hanging indent
  E128, # continuation line under-indented for visual indent
